todo_app/urls.py
from django.urls import path

from todo_app.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TagCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskToggleButton,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "tasks/<int:pk>/toggle/",
        TaskToggleButton.as_view(),
        name="toggle-task-status"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo_list"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

from todo_app.views import TaskListView, TagListView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("todo_app.urls", namespace="todo_app")),
]

todo_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = [
            "-is_done", "-created_at"
        ]

    def __str__(self):
        return f"{self.content} - {"Done" if self.is_done else "Not Done"}"

todo_app/forms.py
from django import forms

from todo_app.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }

todo_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View

from todo_app.forms import TaskForm
from todo_app.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags").order_by(
        "is_done", "created_at"
    )


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_app:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_app:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_app:task-list")


class TaskToggleButton(View):

    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_done = not task.is_done
        task.save()
        return redirect("todo_list:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_app:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_app:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_app:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>To Do</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_app:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_app:tag-list' %}">Tags</a></li>
</ul>

templates/todo_app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag "{{ tag.name }}" ?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:tag-list'%}"
       id="cancel" class="btn btn-secondary">
      Cancel
    </a>
  </form>
{% endblock %}

templates/todo_app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_app/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>Tags</h1>
    <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </div>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo_list:tag-update' pk=tag.id %}" class="btn btn-secondary">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'todo_list:tag-delete' pk=tag.id %}" class="btn btn-secondary">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
{% endblock %}

templates/todo_app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task "{{ task.content|slice:":10"}}..." ?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:task-list'%}"
       id="cancel" class="btn btn-secondary">
      Cancel
    </a>
  </form>
{% endblock %}

templates/todo_app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_app/task_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>TODO list</h1>
    <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </div>
  {% for task in task_list %}
        <div class="d-flex justify-content-between align-items-center">
      <p>
        <strong>
          {{ task.content }} -
          {% if task.is_done %}
            <span style="color: green;">Done</span>
          {% else %}
            <span style="color: red;">Not Done</span>
          {% endif %}
        </strong>
      </p>
      <a href="{% url 'todo_list:toggle-task-status' pk=task.id %}"
         class="btn {% if task.is_done %}btn-secondary{% else %}btn-success{% endif %}">
        {% if task.is_done %}
          Undo
        {% else %}
          Complete
        {% endif %}
      </a>
    </div>
    <p style="font-size: 80%; color: grey;">
      <strong>Created: {{ task.created_at|date:"F d, Y H:i" }}</strong>
      {% if task.deadline %}
        <span style="color: maroon;">
          <strong>Deadline: {{ task.deadline|date:"F d, Y H:i" }}</strong>
        </span>
      {% endif %}
    </p>
    <p>
      Tags: {% for tag in task.tags.all %}{{ tag.name }} {% endfor %}
      <span class="ml-2">
        <a href="{% url 'todo_list:task-update' pk=task.id %}" style="text-decoration: none;">Update</a>
        <a href="{% url 'todo_list:task-delete' pk=task.id %}" style="text-decoration: none;">Delete</a>
      </span>
    </p>
    <br><hr style="background-color: darkgrey; height: 2px; border: none;">
  {% endfor %}
{% endblock %}